"""
session_forecast.py — session-level vial demand forecasting for barangay
anti-rabies vaccination drives.

Thesis component: "Predictive and Retrieval-Augmented Decision Support for
Municipal Companion Animal Services: An ARIMA-RAG Integrated Framework"

WHY THIS MODULE EXISTS
----------------------
forecast_engine.py forecasts the MONTHLY municipal total. Validation on the
reconciled MAO Pagsanjan series (n=19, Jan 2025 - Aug 2026) showed that model
losing to naive persistence on every configuration tried:

    ARIMAX             MAE 471.6
    Naive              MAE 419.0
    LinearRegression   MAE 351.2
    SeasonalNaive      MAE 275.3

The monthly series is not generated by a monthly process. It is a downstream
function of provincial vaccine allocation, which is annual, exogenous, and
gated by liquidation of the prior release. Seven of twenty months are hard
zeros caused by supply outages, not by absent demand.

This module therefore forecasts the unit the office ACTUALLY decides on:
how many vials to carry to one barangay on one session day.

WHY A DISTRIBUTION AND NOT A POINT ESTIMATE
-------------------------------------------
Leave-one-out cross-validation over 32 recorded sessions:

    median of all sessions       MAE  71.1 doses (7.1 vials)
    mean of all sessions         MAE  72.5 doses
    linear on dog+cat population MAE  75.0 doses
    linear on dog population     MAE  75.5 doses
    population + campaign dummy  MAE  76.9 doses
    barangay's own history       MAE  87.8 doses

No predictor beats the median. Two reasons, both documented:

  1. The barangay dog/cat population submitted to the province is derived from
     the PREVIOUS YEAR'S VACCINATION COUNT adjusted by field judgement
     (Session 2 interview, 2:10). Regressing doses on it regresses the target
     on a transformation of itself, and it carries the target's noise without
     adding independent signal.

  2. Session size is set by how far a crew gets in a day, not by how many
     animals live in the barangay. A house-to-house sweep stops when the heat
     sets in or the guides tire, and the barangay is revisited (Session 2,
     3:40). Cabanbanan alone records 12, 170, 173, 180 and 272 doses across
     separate visits to the same barangay.

Point forecasting is therefore not supportable on this data. What IS
supportable is a service level: carry enough vials that the probability of
running short is acceptable. That is the real operational question, because
an opened vial must be finished the same day (Session 2, 21:20) and a vial
holds ten doses (Session 2, 1:15).

Dependencies: numpy (optional - falls back to pure Python)
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field, asdict
from typing import Optional, Sequence

from database import get_db_connection

DOSES_PER_VIAL = 10

# Minimum sessions before a barangay-specific quantile is used instead of the
# municipality-wide one. Below this the barangay's own history is noisier than
# the pooled distribution (LOO-CV above: 87.8 vs 71.1 MAE).
MIN_BARANGAY_SESSIONS = 6

# Default planning service level. 0.75 means: carry enough that roughly three
# sessions in four are fully covered.
DEFAULT_SERVICE_LEVEL = 0.75


@dataclass
class SessionForecast:
    """Vial recommendation for a single planned barangay session."""
    barangay: str
    service_level: float

    recommended_vials: int = 0
    recommended_doses: int = 0

    median_doses: float = 0.0
    p25_doses: float = 0.0
    p75_doses: float = 0.0
    min_doses: float = 0.0
    max_doses: float = 0.0

    basis: str = ""                 # "barangay" or "municipal"
    n_sessions_used: int = 0
    n_sessions_barangay: int = 0

    shortfall_risk_pct: float = 0.0  # P(demand > recommended), empirical
    expected_waste_doses: float = 0.0

    warnings: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)

    def summary(self) -> str:
        return (
            f"{self.barangay}: carry {self.recommended_vials} vials "
            f"({self.recommended_doses} doses) at {self.service_level:.0%} "
            f"service level. Typical session {self.median_doses:.0f} doses "
            f"(IQR {self.p25_doses:.0f}-{self.p75_doses:.0f}). "
            f"Shortfall risk {self.shortfall_risk_pct:.0f}%."
        )


CREATE_SESSIONS = """
CREATE TABLE IF NOT EXISTS vaccination_sessions (
    id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    barangay           VARCHAR(64)  NOT NULL,
    session_date       DATE         NULL,
    doses_administered INT          NOT NULL,
    vials_used         DECIMAL(6,1) NULL,
    vials_requested    INT          NULL,
    request_date       DATE         NULL,
    source_doc         VARCHAR(255) NULL,
    notes              VARCHAR(512) NULL,
    encoded_at         DATETIME     NOT NULL,
    KEY idx_brgy (barangay),
    KEY idx_date (session_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""


def load_sessions(barangay: Optional[str] = None) -> list[tuple[str, int]]:
    """Return [(barangay, doses), ...] for all recorded sessions."""
    conn = get_db_connection()
    try:
        cur = conn.cursor()
        cur.execute(CREATE_SESSIONS)
        if barangay:
            cur.execute(
                "SELECT barangay, doses_administered FROM vaccination_sessions "
                "WHERE barangay = %s AND doses_administered > 0", (barangay,))
        else:
            cur.execute(
                "SELECT barangay, doses_administered FROM vaccination_sessions "
                "WHERE doses_administered > 0")
        rows = [(r[0], int(r[1])) for r in cur.fetchall()]
        cur.close()
        return rows
    finally:
        conn.close()


def _quantile(sorted_vals: Sequence[float], q: float) -> float:
    """Linear-interpolated empirical quantile. No numpy dependency."""
    if not sorted_vals:
        return 0.0
    if len(sorted_vals) == 1:
        return float(sorted_vals[0])
    pos = (len(sorted_vals) - 1) * q
    lo = math.floor(pos)
    hi = math.ceil(pos)
    if lo == hi:
        return float(sorted_vals[int(pos)])
    return float(sorted_vals[lo] + (sorted_vals[hi] - sorted_vals[lo]) * (pos - lo))


def forecast_session(
    barangay: str,
    service_level: float = DEFAULT_SERVICE_LEVEL,
    sessions: Optional[list[tuple[str, int]]] = None,
) -> SessionForecast:
    """
    Recommend a vial count for one planned barangay session.

    The recommendation is the empirical quantile of recorded session sizes at
    the requested service level, rounded UP to a whole vial. Rounding up is
    deliberate: a partly used vial is finished the same day anyway, whereas
    running short turns owners away.
    """
    notes: list[str] = []
    if not 0.0 < service_level < 1.0:
        raise ValueError("service_level must be strictly between 0 and 1")

    all_sessions = sessions if sessions is not None else load_sessions()
    if not all_sessions:
        return SessionForecast(
            barangay=barangay, service_level=service_level,
            warnings=["No recorded sessions; cannot form a recommendation."])

    from barangays import norm_barangay
    key = norm_barangay(barangay)
    own = sorted(d for b, d in all_sessions if norm_barangay(b) == key)
    pooled = sorted(d for _, d in all_sessions)

    # Prefer the barangay's own distribution only when it is long enough to be
    # less noisy than the pooled one. See MIN_BARANGAY_SESSIONS.
    if len(own) >= MIN_BARANGAY_SESSIONS:
        dist, basis = own, "barangay"
    else:
        dist, basis = pooled, "municipal"
        if own:
            notes.append(
                f"{barangay} has only {len(own)} recorded session(s); municipal "
                f"distribution used. A barangay's own history was the weakest "
                f"predictor in validation (MAE 87.8 vs 71.1 doses).")
        else:
            notes.append(
                f"No recorded sessions for {barangay}; municipal distribution used.")

    target_doses = _quantile(dist, service_level)
    vials = max(1, math.ceil(target_doses / DOSES_PER_VIAL))
    doses = vials * DOSES_PER_VIAL

    over = sum(1 for d in dist if d > doses)
    shortfall = 100.0 * over / len(dist)
    waste = sum(max(0, doses - d) for d in dist) / len(dist)

    if len(dist) < 10:
        notes.append(
            f"Only {len(dist)} session(s) in the reference distribution; "
            f"interval is wide and the recommendation is indicative.")

    notes.append(
        "Session size is driven by crew capacity, weather and supply timing "
        "rather than barangay animal population; treat this as a planning "
        "range, not a prediction.")

    return SessionForecast(
        barangay=barangay,
        service_level=service_level,
        recommended_vials=vials,
        recommended_doses=doses,
        median_doses=_quantile(dist, 0.50),
        p25_doses=_quantile(dist, 0.25),
        p75_doses=_quantile(dist, 0.75),
        min_doses=float(dist[0]),
        max_doses=float(dist[-1]),
        basis=basis,
        n_sessions_used=len(dist),
        n_sessions_barangay=len(own),
        shortfall_risk_pct=round(shortfall, 1),
        expected_waste_doses=round(waste, 1),
        warnings=notes,
    )


def forecast_drive(
    barangays: Sequence[str],
    service_level: float = DEFAULT_SERVICE_LEVEL,
) -> dict:
    """
    Vial plan for a multi-barangay drive — the figures that go into the
    request letter to the Office of the Provincial Veterinarian.
    """
    sessions = load_sessions()
    per = [forecast_session(b, service_level, sessions) for b in barangays]
    total_vials = sum(f.recommended_vials for f in per)
    return {
        "service_level": service_level,
        "barangays": [f.to_dict() for f in per],
        "total_vials_requested": total_vials,
        "total_doses": total_vials * DOSES_PER_VIAL,
        "letter_lines": [
            f"{f.recommended_vials} vials Brgy. {f.barangay}" for f in per
        ],
    }


def service_level_table(sessions: Optional[list[tuple[str, int]]] = None) -> list[dict]:
    """
    Trade-off table: service level vs vials carried, shortfall risk and waste.
    Intended for the Chapter 4 discussion and for the dashboard.
    """
    all_sessions = sessions if sessions is not None else load_sessions()
    dist = sorted(d for _, d in all_sessions)
    if not dist:
        return []
    out = []
    for sl in (0.50, 0.60, 0.75, 0.90, 0.95):
        doses = max(1, math.ceil(_quantile(dist, sl) / DOSES_PER_VIAL)) * DOSES_PER_VIAL
        over = sum(1 for d in dist if d > doses)
        out.append({
            "service_level": sl,
            "vials": doses // DOSES_PER_VIAL,
            "doses": doses,
            "shortfall_risk_pct": round(100.0 * over / len(dist), 1),
            "expected_waste_doses": round(
                sum(max(0, doses - d) for d in dist) / len(dist), 1),
        })
    return out


if __name__ == "__main__":
    for row in service_level_table():
        print(row)
